# -*- coding: utf-8 -*-
"""Model_Evaluate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nOrrU-YFyK2SqIqSUUkTB-u5hBW-b0qr
"""

from google.colab import drive
drive.mount('/content/gdrive')

import gym
from gym import spaces
from gym.wrappers import TimeLimit
import tensorflow as tf
import numpy as np
import os
os.environ.setdefault('PATH', '')
import cv2
cv2.ocl.setUseOpenCL(False)
# import dill as pickle
import pickle

from collections import deque
import random

class FireResetEnv(gym.Wrapper):
    def __init__(self, env):
        """Take action on reset for environments that are fixed until firing."""
        gym.Wrapper.__init__(self, env)
        assert env.unwrapped.get_action_meanings()[1] == 'FIRE'
        assert len(env.unwrapped.get_action_meanings()) >= 3

    def reset(self, **kwargs):
        self.env.reset(**kwargs)
        obs, _, done, _ = self.env.step(1)
        if done:
            self.env.reset(**kwargs)
        obs, _, done, _ = self.env.step(2)
        if done:
            self.env.reset(**kwargs)
        return obs

    def step(self, ac):
        return self.env.step(ac)

class EpisodicLifeEnv(gym.Wrapper):
    def __init__(self, env):
        """Make end-of-life == end-of-episode, but only reset on true game over.
        Done by DeepMind for the DQN and co. since it helps value estimation.
        """
        gym.Wrapper.__init__(self, env)
        self.lives = 0
        self.was_real_done  = True

    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        self.was_real_done = done
        # check current lives, make loss of life terminal,
        # then update lives to handle bonus lives
        lives = self.env.unwrapped.ale.lives()
        if lives < self.lives and lives > 0:
            # for Qbert sometimes we stay in lives == 0 condition for a few frames
            # so it's important to keep lives > 0, so that we only reset once
            # the environment advertises done.
            done = True
        self.lives = lives
        return obs, reward, done, info

    def reset(self, **kwargs):
        """Reset only when lives are exhausted.
        This way all states are still reachable even though lives are episodic,
        and the learner need not know about any of this behind-the-scenes.
        """
        if self.was_real_done:
            obs = self.env.reset(**kwargs)
        else:
            # no-op step to advance from terminal/lost life state
            obs, _, _, _ = self.env.step(0)
        self.lives = self.env.unwrapped.ale.lives()
        return obs
class NoopResetEnv(gym.Wrapper):
    def __init__(self, env, noop_max=30):
        """Sample initial states by taking random number of no-ops on reset.
        No-op is assumed to be action 0.
        """
        gym.Wrapper.__init__(self, env)
        self.noop_max = noop_max
        self.override_num_noops = None
        self.noop_action = 0
        assert env.unwrapped.get_action_meanings()[0] == 'NOOP'

    def reset(self, **kwargs):
        """ Do no-op action for a number of steps in [1, noop_max]."""
        self.env.reset(**kwargs)
        if self.override_num_noops is not None:
            noops = self.override_num_noops
        else:
            noops = self.unwrapped.np_random.randint(1, self.noop_max + 1) #pylint: disable=E1101
        assert noops > 0
        obs = None
        for _ in range(noops):
            obs, _, done, _ = self.env.step(self.noop_action)
            if done:
                obs = self.env.reset(**kwargs)
        return obs

    def step(self, ac):
        return self.env.step(ac)
class MaxAndSkipEnv(gym.Wrapper):
    def __init__(self, env, skip=4):
        """Return only every `skip`-th frame"""
        gym.Wrapper.__init__(self, env)
        # most recent raw observations (for max pooling across time steps)
        self._obs_buffer = np.zeros((2,)+env.observation_space.shape, dtype=np.uint8)
        self._skip       = skip
        if skip > 1:
            assert 'NoFrameskip' in env.spec.id, 'disable frame-skipping in the original env. for more than one' \
                                                 ' frame-skip as it will be done by the wrapper'

    def step(self, action):
        """Repeat action, sum reward, and max over last observations."""
        total_reward = 0.0
        done = None
        for i in range(self._skip):
            obs, reward, done, info = self.env.step(action)
            if i == self._skip - 2: self._obs_buffer[0] = obs
            if i == self._skip - 1: self._obs_buffer[1] = obs
            total_reward += reward
            if done:
                break
        # Note that the observation on the done=True frame
        # doesn't matter
        max_frame = self._obs_buffer.max(axis=0)

        return max_frame, total_reward, done, info

    def reset(self, **kwargs):
        return self.env.reset(**kwargs)
class ClipRewardEnv(gym.RewardWrapper):
    def __init__(self, env):
        gym.RewardWrapper.__init__(self, env)

    def reward(self, reward):
        """Bin reward to {+1, 0, -1} by its sign."""
        return np.sign(reward)


class WarpFrame(gym.ObservationWrapper):
    def __init__(self, env, width=84, height=84, grayscale=True, dict_space_key=None):
        """
        Warp frames to 84x84 as done in the Nature paper and later work.
        If the environment uses dictionary observations, `dict_space_key` can be specified which indicates which
        observation should be warped.
        """
        super().__init__(env)
        self._width = width
        self._height = height
        self._grayscale = grayscale
        self._key = dict_space_key
        if self._grayscale:
            num_colors = 1
        else:
            num_colors = 3

        new_space = gym.spaces.Box(
            low=0,
            high=255,
            shape=(self._height, self._width, num_colors),
            dtype=np.uint8,
        )
        if self._key is None:
            original_space = self.observation_space
            self.observation_space = new_space
        else:
            original_space = self.observation_space.spaces[self._key]
            self.observation_space.spaces[self._key] = new_space
        assert original_space.dtype == np.uint8 and len(original_space.shape) == 3

    def observation(self, obs):
        if self._key is None:
            frame = obs
        else:
            frame = obs[self._key]

        if self._grayscale:
            frame = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
        frame = cv2.resize(
            frame, (self._width, self._height), interpolation=cv2.INTER_AREA
        )
        if self._grayscale:
            frame = np.expand_dims(frame, -1)

        if self._key is None:
            obs = frame
        else:
            obs = obs.copy()
            obs[self._key] = frame
        return obs

class ScaledFloatFrame(gym.ObservationWrapper):
    def __init__(self, env):
        gym.ObservationWrapper.__init__(self, env)
        self.observation_space = gym.spaces.Box(low=0, high=1, shape=env.observation_space.shape, dtype=np.float32)

    def observation(self, observation):
        # careful! This undoes the memory optimization, use
        # with smaller replay buffers only.
        return np.array(observation).astype(np.float32) / 255.0

class FrameStack(gym.Wrapper):
    def __init__(self, env, k):
        """Stack k last frames.
        Returns lazy array, which is much more memory efficient.
        See Also
        --------
        baselines.common.atari_wrappers.LazyFrames
        """
        gym.Wrapper.__init__(self, env)
        self.k = k
        self.frames = deque([], maxlen=k)
        shp = env.observation_space.shape
        self.observation_space = spaces.Box(low=0, high=255, shape=(shp[:-1] + (shp[-1] * k,)), dtype=env.observation_space.dtype)

    def reset(self):
        ob = self.env.reset()
        for _ in range(self.k):
            self.frames.append(ob)
        return self._get_ob()

    def step(self, action):
        ob, reward, done, info = self.env.step(action)
        self.frames.append(ob)
        return self._get_ob(), reward, done, info

    def _get_ob(self):
        assert len(self.frames) == self.k
        return LazyFrames(list(self.frames))


class LazyFrames(object):
    def __init__(self, frames):
        """This object ensures that common frames between the observations are only stored once.
        It exists purely to optimize memory usage which can be huge for DQN's 1M frames replay
        buffers.
        This object should only be converted to numpy array before being passed to the model.
        You'd not believe how complex the previous solution was."""
        self._frames = frames
        self._out = None

    def _force(self):
        if self._out is None:
            self._out = np.concatenate(self._frames, axis=-1)
            self._frames = None
        return self._out

    def __array__(self, dtype=None):
        out = self._force()
        if dtype is not None:
            out = out.astype(dtype)
        return out

    def __len__(self):
        return len(self._force())

    def __getitem__(self, i):
        return self._force()[i]

    def count(self):
        frames = self._force()
        return frames.shape[frames.ndim - 1]

    def frame(self, i):
        return self._force()[..., i]
def wrap_deepmind(env, episode_life=True, clip_rewards=True, frame_stack=True, scale=False):
    """Configure environment for DeepMind-style Atari.
    """
    if episode_life:
        env = EpisodicLifeEnv(env)
    if 'FIRE' in env.unwrapped.get_action_meanings():
        env = FireResetEnv(env)
    env = WarpFrame(env)
    if scale:
        env = ScaledFloatFrame(env)
    if clip_rewards:
        env = ClipRewardEnv(env)
    if frame_stack:
        env = FrameStack(env, 4)
    return env
def make_atari(env_id, max_episode_steps=None):
    env = gym.make(env_id)
    env = NoopResetEnv(env, noop_max=30)
    env = MaxAndSkipEnv(env, skip=4)
    if max_episode_steps is not None:
        env = TimeLimit(env, max_episode_steps=max_episode_steps)
    env = wrap_deepmind(env)
    return env

def save_file(file_name, my_list):
    with open(file_name, 'w') as f:
        for single_element in my_list:
            f.write(str(single_element))
            f.write('\n')
            
def save_pickle(file_name, data):
    with open(file_name, 'wb') as f:
        pickle.dump(data, f)

def read_pickle(file_path):
    with open(file_path, 'rb') as f:
        data = pickle.load(f)
    return data

def sample_action(policy, action_size):
    all_actions = np.arange(action_size)
    return np.random.choice(all_actions, p=policy)

class Conv_Layer:
    def __init__(self, num_input_channels, num_filters, filter_shape, filter_stride, name, padding='VALID'):
        self.name = name
        self.filter_stride = filter_stride
        self.padding = padding
        self.conv_filt_shape = (filter_shape, filter_shape, num_input_channels, num_filters)
        self.initializer = tf.keras.initializers.HeNormal()
        self.weights = tf.Variable(self.initializer(shape=self.conv_filt_shape), name=self.name+'_W')
        self.bias = tf.Variable(self.initializer(shape=(1, num_filters)), name=self.name+'_b')
    
    def compute(self, input_data):
        # setup the convolutional layer operation
        output = tf.nn.conv2d(input_data, self.weights, [1, self.filter_stride, self.filter_stride, 1], padding=self.padding)
        # add the bias
        output += self.bias
        # apply a ReLU non-linear activation
        output = tf.nn.relu(output)

        return output
        

class Dense_Layer:
    def __init__(self, num_input_neurons, num_output_neurons, name):
        self.name = name
        self.initializer = tf.keras.initializers.HeNormal()
        self.weights = tf.Variable(self.initializer(shape=(num_input_neurons, num_output_neurons)), name=name+'_W')
        self.bias = tf.Variable(self.initializer(shape=(1, num_output_neurons)), name=name+'_b')
    
    def compute(self, input_data):
        output = tf.matmul(input_data, self.weights) + self.bias
        return output


class NN_DQN:
    def __init__(self, num_actions_env, nn_name):
        self.layer_1 = Conv_Layer(4, 32, 8, 4, name=nn_name+'_conv_1')
        self.layer_2 = Conv_Layer(32, 64, 4, 2, name=nn_name+'_conv_2')
        self.layer_3 = Conv_Layer(64, 64, 3, 1, name=nn_name+'_conv_3')
        self.layer_4 = Dense_Layer(7 * 7 * 64, 512, name=nn_name+'_dense_1')
        self.layer_5 = Dense_Layer(512, num_actions_env, name=nn_name+'_output')


    def predict(self, input_data):
        x = self.layer_1.compute(input_data)
        x = self.layer_2.compute(x)
        x = self.layer_3.compute(x)
        x = tf.reshape(x, [-1, 7 * 7 * 64])
        x = self.layer_4.compute(x)
        x = tf.nn.relu(x)
        x = self.layer_5.compute(x)
        return x
    
    def calculate_loss(self, predicts, targets):
        h = tf.keras.losses.Huber()
        loss = tf.reduce_mean(h(targets, predicts))
        return loss

    def set_parameters(self, params):
        self.layer_1.weights.assign(params[0].numpy())
        self.layer_1.bias.assign(params[1].numpy())
        self.layer_2.weights.assign(params[2].numpy())
        self.layer_2.bias.assign(params[3].numpy())  
        self.layer_3.weights.assign(params[4].numpy())
        self.layer_3.bias.assign(params[5].numpy())
        self.layer_4.weights.assign(params[6].numpy())
        self.layer_4.bias.assign(params[7].numpy())
        self.layer_5.weights.assign(params[8].numpy())
        self.layer_5.bias.assign(params[9].numpy())

def average_action_value_metric(model, held_out_memory):
    model_updating_predict = model.predict(held_out_memory)
    max_value_batch = np.amax(model_updating_predict, axis=1)
    average_action_value = np.average(max_value_batch)
    return average_action_value

def evaluate_model(env, action_size, model_nn):
    play_steps = 0
    total_reward_list = []
    while play_steps < 10000:
        #### start/restart the game ####
        state = env.reset()
        done = False
        total_reward = 0

        while not done:
            play_steps += 1
            state = tf.convert_to_tensor(state, dtype=tf.float32)
            state = tf.reshape(state, [-1, 84, 84, 4])
            #### select action according to epsilon-greedy ####
            # max_action = np.argmax(model_nn.predict(state), axis=1)
            # policy = 0.05 * (np.ones(action_size)/action_size)
            # policy[max_action] = policy[max_action] + 0.95
            # action = sample_action(policy, action_size)
            action = np.argmax(model_nn.predict(state), axis=1)

            #### play and observe the reward ####
            state, reward, done, _ = env.step(action)

            #### calculate the accumulated rewards ####
            total_reward += reward

            if done:
                total_reward_list.append(total_reward)
    
    average_reward = np.mean(np.array(total_reward_list))

    return average_reward

def random_model(env):
    play_steps = 0
    total_reward_list = []
    while play_steps < 10000:
        #### start/restart the game ####
        env.reset()
        done = False
        total_reward = 0

        while not done:
            play_steps += 1
            #### select a random action and save the experience ####
            action = env.action_space.sample()
            _, reward, done, _ = env.step(action)

            #### calculate the accumulated rewards ####
            total_reward += reward

            if done:
                total_reward_list.append(total_reward)
    
    average_reward = np.mean(np.array(total_reward_list))

    return average_reward

def load_model(action_size, model_name, model_path):
    checkpoint = read_pickle(model_path)
    model_params = checkpoint['params']
    model_nn = NN_DQN(action_size, model_name)
    model_nn.set_parameters(model_params)
    return model_nn

def main(game_name):
    #### set up the environment ####
    env = make_atari(game_name, max_episode_steps=None)
    action_size = env.action_space.n
    average_reward_list = []
    average_action_value_list = []
    held_out_memory = read_pickle('/content/gdrive/My Drive/DQN/DQN_Pong/Memory/held_out_memory.pickle')

    #### load the model ####
    for j in range(1, 133):
        file_path = '/content/gdrive/My Drive/DQN/DQN_Pong/Cloud/{}.pickle'.format(j)
        model = load_model(action_size, 'model_{}'.format(j), file_path)
        # average_reward = evaluate_model(env, action_size, model)
        # average_reward_list.append(average_reward)
        # print('average_reward_{}: '.format(j), average_reward)
        model_updating_predict = model.predict(held_out_memory)
        max_value_batch = np.amax(model_updating_predict, axis=1)
        average_action_value = np.average(max_value_batch)
        average_action_value_list.append(average_action_value)
        print('average_action_value_{}: '.format(j), average_action_value)


    # save_file('/content/gdrive/My Drive/DQN/DQN_Pong/Metric/average_reward_list_cloud.txt', average_reward_list)
    save_file('/content/gdrive/My Drive/DQN/DQN_Pong/Metric/average_action_value_list_cloud_edited.txt', average_action_value_list)
    
    # average_reward_random = random_model(env)
    # print(average_reward_random)

if __name__ == "__main__":
    #### set the name of game ####
    main('PongNoFrameskip-v4')
    # main('BreakoutNoFrameskip-v4')