# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bwNfIlV98sU8knvaf77khP3g_zsutBZq
"""

from google.colab import drive
drive.mount('/content/gdrive')

import matplotlib.pyplot as plt

def read_file(file_path):
    data_list = []
    with open(file_path, 'r') as f:
        data = f.readlines()
    for line in data:
        data_list.append(float(line))
    return data_list

def plot(data, save_path):
    # Plot dataset
    plt.figure()
    plt.xlabel('Training Epochs')
    plt.ylabel('Average Reward per Episode')
    plt.title('Average Reward On Pong')
    plt.plot(data, linewidth=2)
    plt.savefig(save_path, dpi=1000)
    plt.show()

if __name__ == "__main__":
    #### read file ####
    data = read_file('/content/gdrive/My Drive/DQN/DQN_Pong/Metric/average_reward_list_cloud.txt')
    # #### plot the result ####
    plot(data, '/content/gdrive/My Drive/DQN/DQN_Pong/Metric/average_reward_list_cloud.png')